# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_STRATEGY: clone

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - sh ssl_acquire.bash

.job_template: &test_definition
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"

test:1804:
  image: asl:1804
  <<: *test_definition

test:latest:
  image: asl:latest
  <<: *test_definition

